# Generated by Django 5.2.3 on 2025-06-23 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products')),
                ('color', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('bluetooth', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_pic', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('waterproof', models.BooleanField(default=False)),
                ('os', models.CharField(max_length=50)),
                ('technology', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productmodel')),
            ],
        ),
    ]
