# Generated by Django 5.2.3 on 2025-06-24 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalfeature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='product.productmodel'),
        ),
        migrations.AlterField(
            model_name='additionalfeature',
            name='waterproof',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
