# Generated by Django 5.2.3 on 2025-06-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_additionalfeature_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.FileField(upload_to='products'),
        ),
    ]
