# Generated by Django 5.2.3 on 2025-06-24 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='slug',
        ),
    ]
