# Generated by Django 5.2.3 on 2025-06-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_productmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='image',
        ),
    ]
