# Generated by Django 5.2.3 on 2025-07-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_offer',
            field=models.BooleanField(default=True),
        ),
    ]
