# Generated by Django 5.2.3 on 2025-07-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_productmodel_category'),
        ('product', '0014_comment'),
    ]

    operations = [
    ]
