<<<<<<< HEAD
# Generated by Django 5.2.3 on 2025-07-07 17:57
=======
# Generated by Django 5.2.3 on 2025-07-07 18:04
>>>>>>> product

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('product', '0015_merge_0013_productmodel_category_0014_comment'),
=======
        ('product', '0015_comment_image'),
>>>>>>> product
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
