# Generated by Django 5.2.3 on 2025-07-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_comment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalfeature',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
