# Generated by Django 5.2.3 on 2025-07-09 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_productmodel_likes_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
